# -*- coding: utf-8 -*-
"""EDA Projectp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEaj8KPKf6-tI89MUYV7cDqSix6WSJgI
"""

import pandas as pd
import matplotlib.pyplot as plt

n = int(input("Enter number of rows: "))

data = {
    "Age": [],
    "Salary": [],
    "Experience": []
}

for i in range(n):
    print(f"\nEnter details for Person {i+1}")
    age = int(input("Age: "))
    salary = float(input("Salary: "))
    exp = float(input("Experience (Years): "))

    data["Age"].append(age)
    data["Salary"].append(salary)
    data["Experience"].append(exp)

df = pd.DataFrame(data)

print("\nDataset:")
print(df)

print("\nStatistical Summary:")
print(df.describe())
print("\nCorrelation Matrix:")
print(df.corr())

df.hist(figsize=(8, 5))
plt.suptitle("Feature Distributions")
plt.show()

plt.figure(figsize=(6, 4))
plt.imshow(df.corr(), cmap='coolwarm')
plt.colorbar()

plt.xticks(range(len(df.columns)), df.columns)
plt.yticks(range(len(df.columns)), df.columns)

for i in range(len(df.columns)):
    for j in range(len(df.columns)):
        plt.text(j, i,
                 round(df.corr().iloc[i, j], 2),
                 ha='center')

plt.title("Correlation Heatmap")
plt.show()

print("\n===== EDA REPORT =====")
print("Total Records:", len(df))
print("Average Age:", round(df["Age"].mean(), 2))
print("Average Salary:", round(df["Salary"].mean(), 2))
print("Average Experience:", round(df["Experience"].mean(), 2))

highest_corr = df.corr().abs().unstack()
highest_corr = highest_corr[highest_corr < 1].max()

print("Highest Correlation:", round(highest_corr, 2))