# -*- coding: utf-8 -*-
"""Real World time Examplep4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEaj8KPKf6-tI89MUYV7cDqSix6WSJgI
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

n = int(input("Enter number of records: "))

months = []
advertising_spend = []
sales = []

for i in range(n):
    print(f"\nEnter details for Record {i+1}")

    month = int(input("Month: "))
    ad_spend = float(input("Advertising Spend: "))
    sale = float(input("Sales Amount: "))

    months.append(month)
    advertising_spend.append(ad_spend)
    sales.append(sale)

# Create DataFrame
df = pd.DataFrame({
    "Month": months,
    "Advertising_Spend": advertising_spend,
    "Sales": sales
})


print("\nDataset Preview:")
print(df)

print("\nSummary Statistics:")
print(df.describe())


plt.figure(figsize=(8, 5))
plt.plot(df["Month"], df["Sales"], marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(df["Advertising_Spend"], df["Sales"])
plt.title("Advertising Spend vs Sales")
plt.xlabel("Advertising Spend")
plt.ylabel("Sales")
plt.show()

X = df[["Advertising_Spend"]]
y = df["Sales"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("\nModel Performance")
print("MAE:", mean_absolute_error(y_test, predictions))
print("R2 Score:", r2_score(y_test, predictions))


future_ad_spend = float(
    input("\nEnter future Advertising Spend for prediction: ")
)

future_sales = model.predict([[future_ad_spend]])

print(f"Predicted Sales: ${future_sales[0]:,.2f}")

plt.figure(figsize=(8, 5))
plt.scatter(X, y, label="Actual Sales")
plt.plot(X, model.predict(X), label="Regression Line")
plt.xlabel("Advertising Spend")
plt.ylabel("Sales")
plt.title("Sales Prediction Model")
plt.legend()
plt.show()

print("\nConclusion:")
print("Higher advertising spend generally leads to higher sales.")
print("The model can be used to predict future sales.")