# -*- coding: utf-8 -*-
"""student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEaj8KPKf6-tI89MUYV7cDqSix6WSJgI
"""


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Name': ['Aman', 'Sara', 'Rahul', 'Priya', 'Ali',
             'John', 'Sneha', 'Riya', 'Aman', 'Karan'],

    'Department': ['Computer', 'IT', 'Mechanical', 'Computer',
                   'Civil', 'IT', 'Mechanical', 'Computer',
                   'Computer', 'Civil'],

    'Marks': [85, 78, 92, 67, 74,
              88, None, 85, 85, 60],

    'Attendance': [90, 88, 95, 80, 85,
                   92, 89, 90, 90, 70]
}


df = pd.DataFrame(data)
print("Original Dataset:\n")
print(df)
print("\nMissing Values:\n")
print(df.isnull().sum())

df = df.dropna()
df = df.drop_duplicates()

print("\nCleaned Dataset:\n")
print(df)
df.to_csv('clean_data.csv', index=False)

df['Marks'].hist()
plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

df['Department'].value_counts().plot(kind='bar')

plt.title("Department Wise Students")
plt.xlabel("Department")
plt.ylabel("Count")
plt.show()


plt.figure(figsize=(6,4))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

print("\nProject Completed Successfully!")
